--Command to generate External Table script from sqlloader .ctl file
sqlldr userid=system/db_name control=names.ctl external_table=generate_only

--Generated manually with a lot of efforts
CREATE TABLE TEST 
	(PARENT_TABLE_ACTION 			VARCHAR2(1), 
	DLY_TBL_DT_TIM_STMP_R       	RAW(8),
	DLY_TBL_LST_MOD_BY          	VARCHAR2(30),
	DLY_TBL_SEQUENCE_NUM        	NUMBER,
	PRIMARY_OWNER               	VARCHAR2(4),
	SECNDRY_OWNER               	VARCHAR2(4),
	ACCT_NUM                    	NUMBER,
	SOC_SEC_NUM_1                   NUMBER,
	SOC_SEC_NUM_2                   INTEGER)
ORGANIZATION EXTERNAL (
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY STMSLR_WORK_DIR
	ACCESS PARAMETERS
		(RECORDS FIXED 597 DATA IS LITTLE ENDIAN FIELDS 
			(PARENT_TABLE_ACTION  position(1:1),
			DLY_TBL_DT_TIM_STMP_R           position(2:9) RAW(8),
			DLY_TBL_LST_MOD_BY              position(10:21),
			DLY_TBL_SEQUENCE_NUM            position(22:25) INTEGER,
			PRIMARY_OWNER                   position(26:29),
			SECNDRY_OWNER                   position(30:33),
			ACCT_NUM                        position(34:37) INTEGER,
			SOC_SEC_NUM_1                   position(38:41) INTEGER,
			SOC_SEC_NUM_2                   position(42:45) INTEGER
		))
		LOCATION ('SUBSCR_MASTER_DLY2.UNL_SUBR01_20150522'));
		
--Generated by Oracle sqlldr in just one command
CREATE TABLE TEST 
	(PARENT_TABLE_ACTION 			VARCHAR2(1), 
	DLY_TBL_DT_TIM_STMP_R       	RAW(8),
	DLY_TBL_LST_MOD_BY          	VARCHAR2(30),
	DLY_TBL_SEQUENCE_NUM        	NUMBER,
	PRIMARY_OWNER               	VARCHAR2(4),
	SECNDRY_OWNER               	VARCHAR2(4),
	ACCT_NUM                    	NUMBER,
	SOC_SEC_NUM_1                   NUMBER,
	SOC_SEC_NUM_2                   INTEGER)
ORGANIZATION EXTERNAL (
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY STMSLR_WORK_DIR
	ACCESS PARAMETERS
		(RECORDS FIXED 597 CHARACTERSET US7ASCII
		DATA IS LITTLE ENDIAN
		BYTEORDERMARK NOCHECK
		READSIZE 1048576
		FIELDS LDRTRIM
		REJECT ROWS WITH ALL NULL FIELDS 
			(PARENT_TABLE_ACTION  position(1:1),
			DLY_TBL_DT_TIM_STMP_R           position(2:9) RAW(8),
			DLY_TBL_LST_MOD_BY              position(10:21),
			DLY_TBL_SEQUENCE_NUM            position(22:25) INTEGER,
			PRIMARY_OWNER                   position(26:29),
			SECNDRY_OWNER                   position(30:33),
			ACCT_NUM                        position(34:37) INTEGER,
			SOC_SEC_NUM_1                   position(38:41) INTEGER,
			SOC_SEC_NUM_2                   position(42:45) INTEGER
		))
		LOCATION ('SUBSCR_MASTER_DLY2.UNL_SUBR01_20150522'));		
		
